spring.datasource.url=jdbc:postgresql://localhost:5432/db-biblioteca
spring.datasource.username=postgres
spring.datasource.password=123415
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true